#include <iostream>
#include <conio.h>
using namespace std;


int bilangan_1,bilangan_2,hasil;

int main()
{
    cout << "PROGRAM KALKULATOR SEDERHANA \n";
    cout << "Masukan Nilai Bilangan 1 = ";
    cin >> bilangan_1;
    cout << "Masukan Nilai Bilangan 2 = ";
    cin >> bilangan_2;
    cout << "1. Penjumlahan \n";
    cout << "2. pengurangan \n";
    cout << "3. Perkalian \n";
    cout << "4. Pembagian \n";
    cout << "Masukan Operasi";
    cin >>operasi;
    switch (operasi)
    {
        
    }
}